In [2]:
import numpy as np

# carregando os dados com numpy
entradas = np.genfromtxt('iris.data', delimiter=',', usecols=(0,1,2,3))
saidas = np.genfromtxt('iris.data', delimiter=',', usecols=(4))
print(len(entradas))
print(len(saidas))

150
150


In [3]:
'''
Iris-setosa: 0
Iris-versicolor: 1
Iris-virginica: 2
'''

# mostrando as 5 primeiras amostras que são Iris-setosa
print(entradas[:5])
print(saidas[:5])

print('---------------------')

# mostrando as 5 últimas amostras que são de Iris-virginica
print(entradas[-5:])
print(saidas[-5:])

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]
[ 0.  0.  0.  0.  0.]
---------------------
[[ 6.7  3.   5.2  2.3]
 [ 6.3  2.5  5.   1.9]
 [ 6.5  3.   5.2  2. ]
 [ 6.2  3.4  5.4  2.3]
 [ 5.9  3.   5.1  1.8]]
[ 2.  2.  2.  2.  2.]


In [4]:
# vou utilizar 105 amostras para treino sendo 35 de cada classe
entradas_treino = np.concatenate((entradas[:35], entradas[50:85], entradas[100:135]))
saidas_treino = np.concatenate((saidas[:35], saidas[50:85], saidas[100:135]))
print(len(entradas_treino))
print(len(saidas_treino))

105
105


In [5]:
entradas_teste = np.concatenate((entradas[35:50], entradas[85:100], entradas[135:]))
saidas_teste = np.concatenate((saidas[35:50], saidas[85:100], saidas[135:]))
print(len(entradas_teste))
print(len(saidas_teste))

45
45


In [6]:
from pybrain.datasets import SupervisedDataSet
from pybrain.tools.shortcuts import buildNetwork
from pybrain.supervised import BackpropTrainer

In [7]:
treinamento = SupervisedDataSet(4, 1)
for i in range(len(entradas_treino)):
    treinamento.addSample(entradas_treino[i], saidas_treino[i])
print(len(treinamento))
print(treinamento.indim)
print(treinamento.outdim)

105
4
1


In [9]:
# construindo a rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.01, momentum=0.3)

# treinando a rede
for epoca in range(1000):
    trainer.train()
    
# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[-0.109]')
('correct:', '[0     ]')
error:  0.00594080
('out:    ', '[-0.039]')
('correct:', '[0     ]')
error:  0.00075987
('out:    ', '[0.04  ]')
('correct:', '[0     ]')
error:  0.00080436
('out:    ', '[-0.067]')
('correct:', '[0     ]')
error:  0.00227067
('out:    ', '[0.051 ]')
('correct:', '[0     ]')
error:  0.00130489
('out:    ', '[-0.044]')
('correct:', '[0     ]')
error:  0.00096174
('out:    ', '[-0.111]')
('correct:', '[0     ]')
error:  0.00619812
('out:    ', '[-0.056]')
('correct:', '[0     ]')
error:  0.00156396
('out:    ', '[0.084 ]')
('correct:', '[0     ]')
error:  0.00356367
('out:    ', '[0.221 ]')
('correct:', '[0     ]')
error:  0.02440020
('out:    ', '[-0.022]')
('correct:', '[0     ]')
error:  0.00023378
('out:    ', '[0.114 ]')
('correct:', '[0     ]')
error:  0.00651436
('out:    ', '[-0.006]')
('correct:', '[0     ]')
error:  0.00001841
('out:    ', '[0.066 ]')
('correct:', '[0     ]')
error:  0.00220320
('out:    ', '[-

0.013462193810873629

In [13]:
# construindo a rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.005, momentum=0.5)

# treinando a rede
for epoca in range(2000):
    trainer.train()
    
# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[0.002 ]')
('correct:', '[0     ]')
error:  0.00000146
('out:    ', '[-0.011]')
('correct:', '[0     ]')
error:  0.00005868
('out:    ', '[0.009 ]')
('correct:', '[0     ]')
error:  0.00004474
('out:    ', '[0.031 ]')
('correct:', '[0     ]')
error:  0.00046851
('out:    ', '[0.02  ]')
('correct:', '[0     ]')
error:  0.00020176
('out:    ', '[0.025 ]')
('correct:', '[0     ]')
error:  0.00030072
('out:    ', '[0.123 ]')
('correct:', '[0     ]')
error:  0.00760076
('out:    ', '[0.016 ]')
('correct:', '[0     ]')
error:  0.00012982
('out:    ', '[0.179 ]')
('correct:', '[0     ]')
error:  0.01604976
('out:    ', '[0.111 ]')
('correct:', '[0     ]')
error:  0.00613965
('out:    ', '[0.076 ]')
('correct:', '[0     ]')
error:  0.00288381
('out:    ', '[0.003 ]')
('correct:', '[0     ]')
error:  0.00000416
('out:    ', '[0.026 ]')
('correct:', '[0     ]')
error:  0.00034350
('out:    ', '[-0.002]')
('correct:', '[0     ]')
error:  0.00000223
('out:    ', '[0

0.0088070106801563276

In [15]:
# construindo a rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.01, momentum=0.7)

# treinando a rede
for epoca in range(1000):
    trainer.train()
    
# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[0.014 ]')
('correct:', '[0     ]')
error:  0.00009121
('out:    ', '[0.001 ]')
('correct:', '[0     ]')
error:  0.00000078
('out:    ', '[0.023 ]')
('correct:', '[0     ]')
error:  0.00026014
('out:    ', '[0.005 ]')
('correct:', '[0     ]')
error:  0.00001415
('out:    ', '[-0.006]')
('correct:', '[0     ]')
error:  0.00001666
('out:    ', '[-0.02 ]')
('correct:', '[0     ]')
error:  0.00020363
('out:    ', '[0.334 ]')
('correct:', '[0     ]')
error:  0.05587620
('out:    ', '[-0.021]')
('correct:', '[0     ]')
error:  0.00021614
('out:    ', '[0.003 ]')
('correct:', '[0     ]')
error:  0.00000407
('out:    ', '[-0.032]')
('correct:', '[0     ]')
error:  0.00050258
('out:    ', '[0.057 ]')
('correct:', '[0     ]')
error:  0.00162375
('out:    ', '[-0.04 ]')
('correct:', '[0     ]')
error:  0.00078372
('out:    ', '[-0.01 ]')
('correct:', '[0     ]')
error:  0.00004558
('out:    ', '[-0.029]')
('correct:', '[0     ]')
error:  0.00040706
('out:    ', '[0

0.0084265643751142948