In [25]:
import numpy as np

# carregando os dados com numpy
entradas = np.genfromtxt('iris.data', delimiter=',', usecols=(0,1,2,3))
saidas = np.genfromtxt('iris.data', delimiter=',', usecols=(4))
print(len(entradas))
print(len(saidas))

150
150


In [26]:
'''
Iris-setosa: 0
Iris-versicolor: 1
Iris-virginica: 2
'''

# mostrando as 5 primeiras amostras que são Iris-setosa
print(entradas[:5])
print(saidas[:5])

print(' ---------------------- ')

# mostrando as 5 últimas amostras que são Iris-virgínica
print(entradas[-5:])
print(saidas[-5:])

[[ 5.1  3.5  1.4  0.2]
 [ 4.9  3.   1.4  0.2]
 [ 4.7  3.2  1.3  0.2]
 [ 4.6  3.1  1.5  0.2]
 [ 5.   3.6  1.4  0.2]]
[ 0.  0.  0.  0.  0.]
 ---------------------- 
[[ 6.7  3.   5.2  2.3]
 [ 6.3  2.5  5.   1.9]
 [ 6.5  3.   5.2  2. ]
 [ 6.2  3.4  5.4  2.3]
 [ 5.9  3.   5.1  1.8]]
[ 2.  2.  2.  2.  2.]


In [27]:
# vou utilizar 105 amostras para treino sendo 35 de cada classe
entradas_treino = np.concatenate((entradas[:35], entradas[50:85], entradas[100:135]))
saidas_treino = np.concatenate((saidas[:35], saidas[50:85], saidas[100:135]))
print(len(entradas_treino))
print(len(saidas_treino))

105
105


In [28]:
entradas_teste = np.concatenate((entradas[35:50], entradas[85:100], entradas[135:]))
saidas_teste = np.concatenate((saidas[35:50], saidas[85:100], saidas[135:]))
print(len(entradas_teste))
print(len(saidas_teste))

45
45


In [29]:
from pybrain.datasets import SupervisedDataSet
from pybrain.tools.shortcuts import buildNetwork
from pybrain.supervised import BackpropTrainer

In [30]:
treinamento = SupervisedDataSet(4, 1)
for i in range(len(entradas_treino)):
    treinamento.addSample(entradas_treino[i], saidas_treino[i])
print(len(treinamento))
print(treinamento.indim)
print(treinamento.outdim)

105
4
1


In [31]:
# construindo a rede
rede = buildNetwork(treinamento.indim, 2, treinamento.outdim, bias=True)
trainer = BackpropTrainer(rede, treinamento, learningrate=0.01, momentum=0.3)

# treinando a rede
for epoca in range(1000):
    trainer.train()
    
# testando a rede
teste = SupervisedDataSet(4, 1)
for i in range(len(entradas_teste)):
    teste.addSample(entradas_teste[i], saidas_teste[i])
trainer.testOnData(teste, verbose=True)


Testing on data:
('out:    ', '[0.014 ]')
('correct:', '[0     ]')
error:  0.00009719
('out:    ', '[0.005 ]')
('correct:', '[0     ]')
error:  0.00001315
('out:    ', '[0.019 ]')
('correct:', '[0     ]')
error:  0.00018709
('out:    ', '[0.03  ]')
('correct:', '[0     ]')
error:  0.00044108
('out:    ', '[0.013 ]')
('correct:', '[0     ]')
error:  0.00008598
('out:    ', '[0.012 ]')
('correct:', '[0     ]')
error:  0.00006885
('out:    ', '[0.073 ]')
('correct:', '[0     ]')
error:  0.00264582
('out:    ', '[0.023 ]')
('correct:', '[0     ]')
error:  0.00026383
('out:    ', '[0.032 ]')
('correct:', '[0     ]')
error:  0.00052613
('out:    ', '[0.019 ]')
('correct:', '[0     ]')
error:  0.00018603
('out:    ', '[0.031 ]')
('correct:', '[0     ]')
error:  0.00048639
('out:    ', '[0.007 ]')
('correct:', '[0     ]')
error:  0.00002188
('out:    ', '[0.022 ]')
('correct:', '[0     ]')
error:  0.00024718
('out:    ', '[0.006 ]')
('correct:', '[0     ]')
error:  0.00001570
('out:    ', '[0

0.010058305516675635